[main]
api_key = "304082431:AAEfcwuTMIPuxzQb1F7WfPAezmpheXLMbtU"
debug = false
static_path = "static"
maximum_flood_level = 5

[http]
addr = "localhost:8080"

[pgsql]
dsn = "postgres://gotb:gotb@localhost/gotb?sslmode=disable"

[log]
level = "debug"

[cache]
duration = "5m"
update_period = "60s"

[feeds]
update_period = "5s"
